[2013-12-23 11:31:17] log.ERROR: exception 'ErrorException' with message 'The use statement with non-compound name 'Input' has no effect' in /www/dev/evasive-cactuar/app/controllers/CommentsController.php:3
Stack trace:
#0 /www/dev/evasive-cactuar/vendor/composer/ClassLoader.php(185): Illuminate\Exception\Handler->handleError(2, 'The use stateme...', '/www/dev/evasiv...', 3, Array)
#1 /www/dev/evasive-cactuar/vendor/composer/ClassLoader.php(185): Composer\Autoload\ClassLoader::loadClass()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('CommentsControl...')
#3 [internal function]: spl_autoload_call('CommentsControl...')
#4 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Container/Container.php(308): ReflectionClass->__construct('CommentsControl...')
#5 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Container/Container.php(250): Illuminate\Container\Container->build('CommentsControl...', Array)
#6 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(480): Illuminate\Container\Container->make('CommentsControl...', Array)
#7 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(983): Illuminate\Foundation\Application->make('CommentsControl...')
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#9 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#10 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#11 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 /www/dev/evasive-cactuar/public/index.php(49): Illuminate\Foundation\Application->run()
#15 {main} [] []
[2013-12-23 11:31:51] log.ERROR: exception 'ErrorException' with message 'The use statement with non-compound name 'Input' has no effect' in /www/dev/evasive-cactuar/app/controllers/CommentsController.php:3
Stack trace:
#0 /www/dev/evasive-cactuar/vendor/composer/ClassLoader.php(185): Illuminate\Exception\Handler->handleError(2, 'The use stateme...', '/www/dev/evasiv...', 3, Array)
#1 /www/dev/evasive-cactuar/vendor/composer/ClassLoader.php(185): Composer\Autoload\ClassLoader::loadClass()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('CommentsControl...')
#3 [internal function]: spl_autoload_call('CommentsControl...')
#4 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Container/Container.php(308): ReflectionClass->__construct('CommentsControl...')
#5 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Container/Container.php(250): Illuminate\Container\Container->build('CommentsControl...', Array)
#6 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(480): Illuminate\Container\Container->make('CommentsControl...', Array)
#7 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(983): Illuminate\Foundation\Application->make('CommentsControl...')
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#9 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#10 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#11 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 /www/dev/evasive-cactuar/public/index.php(49): Illuminate\Foundation\Application->run()
#15 {main} [] []
[2013-12-23 11:33:08] log.ERROR: exception 'ErrorException' with message 'The use statement with non-compound name 'Redirect' has no effect' in /www/dev/evasive-cactuar/app/controllers/CommentsController.php:3
Stack trace:
#0 /www/dev/evasive-cactuar/vendor/composer/ClassLoader.php(185): Illuminate\Exception\Handler->handleError(2, 'The use stateme...', '/www/dev/evasiv...', 3, Array)
#1 /www/dev/evasive-cactuar/vendor/composer/ClassLoader.php(185): Composer\Autoload\ClassLoader::loadClass()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('CommentsControl...')
#3 [internal function]: spl_autoload_call('CommentsControl...')
#4 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Container/Container.php(308): ReflectionClass->__construct('CommentsControl...')
#5 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Container/Container.php(250): Illuminate\Container\Container->build('CommentsControl...', Array)
#6 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(480): Illuminate\Container\Container->make('CommentsControl...', Array)
#7 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(983): Illuminate\Foundation\Application->make('CommentsControl...')
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#9 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#10 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#11 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 /www/dev/evasive-cactuar/public/index.php(49): Illuminate\Foundation\Application->run()
#15 {main} [] []
[2013-12-23 12:07:28] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1439
Stack trace:
#0 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /www/dev/evasive-cactuar/public/index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-12-23 12:08:19] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1439
Stack trace:
#0 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /www/dev/evasive-cactuar/public/index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-12-23 12:09:25] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1439
Stack trace:
#0 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /www/dev/evasive-cactuar/public/index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-12-23 12:12:06] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1439
Stack trace:
#0 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /www/dev/evasive-cactuar/public/index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-12-23 12:15:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1439
Stack trace:
#0 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /www/dev/evasive-cactuar/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /www/dev/evasive-cactuar/public/index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
