[2013-09-24 14:54:39] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laraveil.users' doesn't exist' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Database\Connection.php:350
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Database\Connection.php(350): PDO->prepare('delete from `us...')
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Database\Connection.php(520): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'delete from `us...', Array)
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Database\Connection.php(355): Illuminate\Database\Connection->run('delete from `us...', Array, Object(Closure))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Database\Connection.php(312): Illuminate\Database\Connection->affectingStatement('delete from `us...', Array)
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1490): Illuminate\Database\Connection->delete('delete from `us...', Array)
#5 D:\vhosts\laraveil\app\database\seeds\SentrySeeder.php(9): Illuminate\Database\Query\Builder->delete()
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Database\Seeder.php(38): SentrySeeder->run()
#7 D:\vhosts\laraveil\app\database\seeds\DatabaseSeeder.php(14): Illuminate\Database\Seeder->call('SentrySeeder')
#8 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Database\Console\SeedCommand.php(53): DatabaseSeeder->run()
#9 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Console\Command.php(108): Illuminate\Database\Console\SeedCommand->fire()
#10 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(244): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Console\Command.php(96): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Application.php(897): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Application.php(191): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 D:\vhosts\laraveil\artisan(59): Symfony\Component\Console\Application->run()
#16 {main}

Next exception 'Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laraveil.users' doesn't exist (SQL: delete from `users`) (Bindings: array (
))' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Database\Connection.php:555
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Database\Connection.php(528): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'delete from `us...', Array)
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Database\Connection.php(355): Illuminate\Database\Connection->run('delete from `us...', Array, Object(Closure))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Database\Connection.php(312): Illuminate\Database\Connection->affectingStatement('delete from `us...', Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1490): Illuminate\Database\Connection->delete('delete from `us...', Array)
#4 D:\vhosts\laraveil\app\database\seeds\SentrySeeder.php(9): Illuminate\Database\Query\Builder->delete()
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Database\Seeder.php(38): SentrySeeder->run()
#6 D:\vhosts\laraveil\app\database\seeds\DatabaseSeeder.php(14): Illuminate\Database\Seeder->call('SentrySeeder')
#7 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Database\Console\SeedCommand.php(53): DatabaseSeeder->run()
#8 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Console\Command.php(108): Illuminate\Database\Console\SeedCommand->fire()
#9 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(244): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Console\Command.php(96): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Application.php(897): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Application.php(191): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 D:\vhosts\laraveil\artisan(59): Symfony\Component\Console\Application->run()
#15 {main} [] []
[2013-09-24 16:17:35] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in D:\vhosts\laraveil\app\routes.php:61
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-24 16:18:11] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ')'' in D:\vhosts\laraveil\app\routes.php:64
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-24 16:18:42] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ')'' in D:\vhosts\laraveil\app\routes.php:71
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-24 16:19:10] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';', expecting ')'' in D:\vhosts\laraveil\app\routes.php:71
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-24 16:19:50] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in D:\vhosts\laraveil\app\routes.php:71
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-24 16:21:26] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '{', expecting ')'' in D:\vhosts\laraveil\app\routes.php:60
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-24 16:22:36] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in D:\vhosts\laraveil\app\routes.php:69
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-24 17:11:11] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'route' (T_STRING), expecting variable (T_VARIABLE) or '$'' in D:\vhosts\laraveil\app\routes.php:68
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-24 17:12:27] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}'' in D:\vhosts\laraveil\app\routes.php:69
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-24 17:17:39] log.ERROR: exception 'ErrorException' with message 'Undefined variable: article' in D:\vhosts\laraveil\app\routes.php:59
Stack trace:
#0 D:\vhosts\laraveil\app\routes.php(59): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\vhosts\larav...', 59, Array)
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\start.php(253): require('D:\vhosts\larav...')
#2 D:\vhosts\laraveil\bootstrap\start.php(61): require('D:\vhosts\larav...')
#3 D:\vhosts\laraveil\artisan(30): require_once('D:\vhosts\larav...')
#4 {main} [] []
[2013-09-24 17:21:39] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=>' (T_DOUBLE_ARROW)' in D:\vhosts\laraveil\app\routes.php:68
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-24 17:55:55] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=>' (T_DOUBLE_ARROW)' in D:\vhosts\laraveil\app\routes.php:73
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-24 18:12:40] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}'' in D:\vhosts\laraveil\app\routes.php:71
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-24 18:13:44] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}'' in D:\vhosts\laraveil\app\routes.php:71
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-24 18:48:17] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ','' in D:\vhosts\laraveil\app\routes.php:55
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
