[2013-09-14 15:18:02] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'D:\vhosts\larav...', 974, Array)
#1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2013-09-14 15:18:17] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:18:29] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:18:36] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'D:\vhosts\larav...', 974, Array)
#1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2013-09-14 15:20:18] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:34:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:34:41] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'D:\vhosts\larav...', 974, Array)
#1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2013-09-14 15:35:51] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'D:\vhosts\larav...', 974, Array)
#1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2013-09-14 15:35:52] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'D:\vhosts\larav...', 974, Array)
#1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2013-09-14 15:47:02] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'D:\vhosts\larav...', 974, Array)
#1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2013-09-14 15:48:00] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'D:\vhosts\larav...', 974, Array)
#1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2013-09-14 15:48:01] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'D:\vhosts\larav...', 974, Array)
#1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2013-09-14 15:48:04] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'D:\vhosts\larav...', 974, Array)
#1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2013-09-14 15:48:05] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'D:\vhosts\larav...', 974, Array)
#1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2013-09-14 15:48:09] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:48:15] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'D:\vhosts\larav...', 974, Array)
#1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2013-09-14 15:48:23] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:48:25] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:48:26] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'D:\vhosts\larav...', 974, Array)
#1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2013-09-14 15:48:32] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:48:52] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'D:\vhosts\larav...', 974, Array)
#1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2013-09-14 15:48:54] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'D:\vhosts\larav...', 974, Array)
#1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2013-09-14 15:49:33] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:49:38] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Controllers\Admin\Notification' not found' in D:\vhosts\laraveil\app\controllers\admin\PagesController.php:51
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-14 15:51:40] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:51:46] log.ERROR: exception 'InvalidArgumentException' with message 'View [admin.pages.show] not found.' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php:123
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php(64): Illuminate\View\FileViewFinder->findInPaths('admin.pages.sho...', Array)
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\View\Environment.php(115): Illuminate\View\FileViewFinder->find('admin.pages.sho...')
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(177): Illuminate\View\Environment->make('admin.pages.sho...')
#3 D:\vhosts\laraveil\app\controllers\admin\PagesController.php(15): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#4 D:\vhosts\laraveil\app\controllers\admin\PagesController.php(15): Illuminate\Support\Facades\View::make('admin.pages.sho...')
#5 [internal function]: App\Controllers\Admin\PagesController->show('1')
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#7 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('show', Array)
#8 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'show', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1')
#10 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#11 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#12 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-09-14 15:51:49] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:51:53] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:52:12] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:52:14] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:52:19] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:52:26] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:52:37] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:52:40] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:52:45] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:53:01] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:53:01] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:53:30] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:53:42] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:55:28] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:55:36] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:55:49] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:56:00] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'D:\vhosts\larav...', 974, Array)
#1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2013-09-14 15:56:04] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:57:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-09-14 15:57:23] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\vhosts\laraveil\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
